version: "3"

tasks:
  build:
    cmds:
      - go build -o build/templify .

  test:
    cmds:
      - go test ./...

  clean:
    cmds:
      - rm -rf build/ examples/*.pdf /tmp/templify-*.pdf

  run:
    cmds:
      - ./build/templify -input examples/example.md -bundle report -output examples/example.pdf -config ./config.yml

  invoice:
    cmds:
      - ./build/templify -input examples/example-invoice.md -bundle invoice -output examples/example-invoice.pdf

  quote:
    cmds:
      - ./build/templify -input examples/example-quote.md -bundle quote -output examples/example-quote.pdf

  default:
    cmds:
      - task: build
      - task: run
